option(TTK_BUILD_PERSISTENCEDIAGRAMCLUSTERING_FILTER "Build the PersistenceDiagramClustering filter" ${TTK_ENABLE_FILTER_DEFAULT})
mark_as_advanced(TTK_BUILD_PERSISTENCEDIAGRAMCLUSTERING_FILTER)

if(${TTK_BUILD_PERSISTENCEDIAGRAMCLUSTERING_FILTER})
  ttk_register_pv_filter(ttkPersistenceDiagramClustering PersistenceDiagramClustering.xml)
endif()

