option(TTK_BUILD_DEPTHIMAGEBASEDGEOMETRYAPPROXIMATION_FILTER "Build the DepthImageBasedGeometryApproximation filter" ${TTK_ENABLE_FILTER_DEFAULT})
mark_as_advanced(TTK_BUILD_DEPTHIMAGEBASEDGEOMETRYAPPROXIMATION_FILTER)

if(${TTK_BUILD_DEPTHIMAGEBASEDGEOMETRYAPPROXIMATION_FILTER})
  ttk_register_pv_filter(ttkDepthImageBasedGeometryApproximation DepthImageBasedGeometryApproximation.xml)
endif()
