name: 'Install dependencies for Unix'
description: 'Install Spectra optional dependencies'
runs:
  using: "composite"
  steps:

    - name: Install Spectra dependency
      shell: bash
      run: |
        wget https://github.com/yixuan/spectra/archive/v1.1.0.tar.gz
        tar xvf v1.1.0.tar.gz
        mkdir build_spectra && cd build_spectra
        cmake ../spectra-1.1.0
        sudo cmake --build . --target install --parallel
